/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir.View;

import java.awt.Window;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import kasir.Controller.BerandaController;
import kasir.Model.Produk;

/**
 *
 * @author AudiAdyan
 */
public class Beranda extends javax.swing.JPanel {

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
        moreComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambahBelanjaan = new javax.swing.JButton();
        printStruk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalBelanjaan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        tambahBelanjaan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tambahBelanjaan.setText("Tambah Belanjaan");
        tambahBelanjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBelanjaanActionPerformed(evt);
            }
        });

        printStruk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printStruk.setText("Print Struk");
        printStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printStrukActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel1.setText("Total");

        totalBelanjaan.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        totalBelanjaan.setText("Rp 0");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(23, 23));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(12, 12));

        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalBelanjaan)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambahBelanjaan, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addGap(15, 15, 15)
                        .addComponent(printStruk, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalBelanjaan))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBelanjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void moreComponents() {
        listBelanjaan = new BerandaController();
    }
    
    private void tambahBelanjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBelanjaanActionPerformed
        window = SwingUtilities.getWindowAncestor(this);
        window.setEnabled(false);
        new PilihProduk(this).setVisible(true);
    }//GEN-LAST:event_tambahBelanjaanActionPerformed

    private void printStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printStrukActionPerformed
        if(listBelanjaan.printStruk()) {
            jPanel1.removeAll();
            listBelanjaan.clearOrders();
            refreshPanel();
            updateTotalHarga();
            JOptionPane.showMessageDialog(this, "Print Struk Berhasil!");
        } else {
            JOptionPane.showMessageDialog(this, "Print Struk Gagal!", "Print Struk", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_printStrukActionPerformed
    
    public void updateBarang(Produk produk) {
        listBelanjaan.addListItem(produk);
        jPanel1.add(new ItemBelanja(listBelanjaan.getLastOrders(), this));
        refreshPanel();
        
        jScrollPane1.validate();
        vertical = jScrollPane1.getVerticalScrollBar();
        vertical.setValue( vertical.getMaximum() + 1 );
        
        updateTotalHarga();
    }
    
    public void updateTotalHarga() {
        totalBelanjaan.setText("Rp " + listBelanjaan.getTotalHarga());
    }
    
    private void refreshPanel() {
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    public Window window;
    public BerandaController listBelanjaan;
    private javax.swing.JScrollBar vertical;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printStruk;
    private javax.swing.JButton tambahBelanjaan;
    private javax.swing.JLabel totalBelanjaan;
    // End of variables declaration//GEN-END:variables
}
