/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir.View;

import kasir.Model.Produk;

/**
 *
 * @author AudiAdyan
 */
public class ItemPilihProduk extends javax.swing.JPanel {

    /**
     * Creates new form ItemPilihProduk
     */
    private Produk produk;
    
    public ItemPilihProduk(Produk produk) {
        initComponents();
        this.produk = produk;
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pilih = new javax.swing.JCheckBox();
        namaBarang = new javax.swing.JLabel();
        hargaBarang = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        namaBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaBarang.setText("Nama");

        hargaBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hargaBarang.setText("Rp 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pilih)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namaBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(hargaBarang)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pilih)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(namaBarang)
                        .addComponent(hargaBarang)))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setData() {
        namaBarang.setText(produk.getNama());
        hargaBarang.setText("Rp " + produk.getHarga());
    }
    
    public Produk getProduk() {
        return produk;
    }
    
    public boolean getStatus() {
        return pilih.isSelected();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hargaBarang;
    private javax.swing.JLabel namaBarang;
    private javax.swing.JCheckBox pilih;
    // End of variables declaration//GEN-END:variables
}
