/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir.View;

import kasir.Model.Order;

/**
 *
 * @author AudiAdyan
 */
public class ItemBelanja extends javax.swing.JPanel {


    /**
     * Creates new form itemBelanja
     */    
    public ItemBelanja(Order order, Beranda beranda) {
        initComponents();
        this.beranda = beranda;
        this.order = order;
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaBarang = new javax.swing.JLabel();
        hargaSatuan = new javax.swing.JLabel();
        minBarang = new javax.swing.JButton();
        addBarang = new javax.swing.JButton();
        jumlahBarang = new javax.swing.JLabel();
        hargaTotal = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        namaBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaBarang.setText("Nama Barang");

        hargaSatuan.setText("Rp 0");

        minBarang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        minBarang.setText("-");
        minBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minBarangActionPerformed(evt);
            }
        });

        addBarang.setText("+");
        addBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBarangActionPerformed(evt);
            }
        });

        jumlahBarang.setText("0");

        hargaTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hargaTotal.setText("Rp 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hargaSatuan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hargaTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namaBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(minBarang)
                        .addGap(15, 15, 15)
                        .addComponent(jumlahBarang)
                        .addGap(15, 15, 15)
                        .addComponent(addBarang)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaBarang)
                    .addComponent(minBarang)
                    .addComponent(addBarang)
                    .addComponent(jumlahBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaSatuan)
                    .addComponent(hargaTotal))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void minBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minBarangActionPerformed
        order.minJumlah();
        if(order.getJumlah() == 0) {
            minBarang.setEnabled(false);
        }
        updateBelanja();
    }//GEN-LAST:event_minBarangActionPerformed

    private void addBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBarangActionPerformed
        if(order.getJumlah() == 0) {
            minBarang.setEnabled(true);
        }
        order.addJumlah();
        updateBelanja();
    }//GEN-LAST:event_addBarangActionPerformed

    private void setData() {
        namaBarang.setText(order.getProduk().getNama());
        hargaSatuan.setText("Rp " + order.getProduk().getHarga());
        updateBelanja();
    }
    
    private void updateBelanja() {
        jumlahBarang.setText(String.format("%d", order.getJumlah()));
        hargaTotal.setText(String.format("Rp %d", order.getJumlah()*order.getProduk().getHarga()));
        beranda.updateTotalHarga();
    }

    private Beranda beranda;
    private Order order;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBarang;
    private javax.swing.JLabel hargaSatuan;
    private javax.swing.JLabel hargaTotal;
    private javax.swing.JLabel jumlahBarang;
    private javax.swing.JButton minBarang;
    private javax.swing.JLabel namaBarang;
    // End of variables declaration//GEN-END:variables
}
